name: Deploy CI/CD

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: Deploy to Production ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::448049815254:role/GithubActionsRepoWebsite
          aws-region: us-east-2

      - name: Login to Amazon ECR for Github Action
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 448049815254.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: website-prod
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
